---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Envoy package is installed
  apt:
    name: "{{ envoy_package }}"
    state: "{{ envoy_package_state }}"

- name: "Create envoy directory"
  file:
    path: /etc/envoy/
    state: directory
    owner: root
    group: root
    mode: "0777"

- name: Add Envoy systemd template
  template:
    src: "envoy.system.j2"
    dest: "/etc/systemd/system/envoy.service"
    owner: root
    group: root
    mode: "0644"
  notify: restart envoy

- name: Add Envoy configuration
  template:
    src: "{{ envoy_configuration_template }}"
    dest: "/etc/envoy/envoy.yaml"
    owner: "{{ envoy_system_user }}"
    group: "{{ envoy_system_group }}"
    mode: "0644"
  notify: restart envoy
